### ISSUE TITLE
AstroConda inclusion?

### ISSUE THREAD

**Issue by jhunkeler** [STScI-JWST/wss_tools#1]
Should I be building this for dev, public, both, or none of the above?

**Comment by pllim** [comment]
Ops, sorry, for some reason, I am not automatically "watching" this repo although I created it (but I am now). Answer for now is "none". @mperrin feels that it is too specialized for Wavefront Sensing to be useful for anything else.

**Comment by pllim** [comment]
Might need to revisit this if #14 becomes a problem. FYI.

**Comment by jhunkeler** [comment]
OK, noted. Just let me know.
