### ISSUE TITLE
request: SNRCalc tool should calculate and display background mean

### ISSUE THREAD

**Issue by mperrin** [STScI-JWST/wss_tools#7]
Request from Scott Knight. In the SNRCalc tool display, where it outputs Background STDEV, it could also display the Background Mean. This would help inform the user if the background is substantially nonzero in which case the user may wish to use the Background Subtraction feature.

**Comment by pllim** [comment]
This is already implemented in `stginga`, which QUIP uses. You can see the update layout [here](http://stginga.readthedocs.io/en/latest/stginga/plugins_manual/snrcalc.html). It should be in AstroConda by the end of the week, the latest.

**Comment by mperrin** [comment]
That was fast! Very nice, thanks.
